// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gauss_blur,hls_ip_2020_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-csg325-1Q,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.685000,HLS_SYN_LAT=4009490,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=2,HLS_SYN_FF=335,HLS_SYN_LUT=682,HLS_VERSION=2020_1}" *)

module gauss_blur (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inImage_dout,
        inImage_empty_n,
        inImage_read,
        gauss_kernel_address0,
        gauss_kernel_ce0,
        gauss_kernel_q0,
        outImage_din,
        outImage_full_n,
        outImage_write
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inImage_dout;
input   inImage_empty_n;
output   inImage_read;
output  [3:0] gauss_kernel_address0;
output   gauss_kernel_ce0;
input  [7:0] gauss_kernel_q0;
output  [7:0] outImage_din;
input   outImage_full_n;
output   outImage_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inImage_read;
reg gauss_kernel_ce0;
reg[7:0] outImage_din;
reg outImage_write;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    inImage_blk_n;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln47_fu_490_p2;
wire   [0:0] and_ln50_fu_508_p2;
reg    outImage_blk_n;
wire    ap_CS_fsm_state10;
wire   [0:0] and_ln68_fu_606_p2;
wire   [0:0] or_ln73_2_fu_639_p2;
wire    ap_CS_fsm_state11;
reg   [0:0] and_ln68_reg_1035;
reg   [0:0] or_ln73_2_reg_1039;
wire   [0:0] icmp_ln14_fu_645_p2;
wire   [1:0] i_fu_345_p2;
reg   [1:0] i_reg_892;
wire    ap_CS_fsm_state2;
wire   [4:0] sub_ln40_fu_367_p2;
reg   [4:0] sub_ln40_reg_897;
wire   [0:0] icmp_ln38_fu_339_p2;
wire   [1:0] j_fu_379_p2;
reg   [1:0] j_reg_959;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln39_fu_373_p2;
wire   [9:0] row_fu_454_p2;
reg   [9:0] row_reg_972;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln50_fu_460_p2;
reg   [0:0] icmp_ln50_reg_977;
wire   [0:0] icmp_ln46_fu_448_p2;
wire   [0:0] icmp_ln68_fu_466_p2;
reg   [0:0] icmp_ln68_reg_982;
wire   [0:0] icmp_ln73_fu_478_p2;
reg   [0:0] icmp_ln73_reg_987;
wire   [0:0] icmp_ln73_1_fu_484_p2;
reg   [0:0] icmp_ln73_1_reg_992;
wire   [8:0] col_fu_496_p2;
reg   [8:0] col_reg_1000;
reg    ap_predicate_op114_read_state7;
reg    ap_block_state7;
wire   [0:0] icmp_ln50_1_fu_502_p2;
reg   [0:0] icmp_ln50_1_reg_1005;
wire   [1:0] i_1_fu_519_p2;
wire    ap_CS_fsm_state8;
reg   [8:0] part_buffer_0_addr_reg_1020;
wire   [0:0] icmp_ln55_fu_513_p2;
wire   [7:0] part_buffer_1_q0;
reg   [7:0] window_1_2_reg_1030;
wire    ap_CS_fsm_state9;
reg    ap_predicate_op169_write_state10;
reg    ap_block_state10;
wire   [1:0] i_2_fu_651_p2;
reg   [1:0] i_2_reg_1046;
reg    ap_predicate_op197_write_state11;
reg    ap_block_state11;
wire   [7:0] tmp_4_fu_675_p5;
reg   [7:0] tmp_4_reg_1051;
wire   [7:0] tmp_5_fu_687_p5;
reg   [7:0] tmp_5_reg_1056;
wire    ap_CS_fsm_state12;
wire   [15:0] mul_ln16_1_fu_798_p2;
reg   [15:0] mul_ln16_1_reg_1081;
wire   [16:0] grp_fu_819_p3;
reg   [16:0] add_ln16_reg_1086;
wire    ap_CS_fsm_state13;
wire   [17:0] grp_fu_827_p3;
reg   [17:0] add_ln16_1_reg_1091;
wire    ap_CS_fsm_state14;
wire   [19:0] add_ln16_2_fu_813_p2;
wire    ap_CS_fsm_state15;
reg    part_buffer_0_ce0;
reg    part_buffer_0_we0;
wire   [7:0] part_buffer_0_q0;
wire   [8:0] part_buffer_1_address0;
reg    part_buffer_1_ce0;
reg    part_buffer_1_we0;
reg   [1:0] i_0_reg_226;
reg   [1:0] j_0_reg_238;
wire    ap_CS_fsm_state5;
reg   [9:0] row_0_reg_250;
reg   [8:0] col_0_reg_261;
reg   [7:0] window_2_2_reg_273;
wire   [1:0] ap_phi_mux_i1_0_phi_fu_290_p4;
reg   [1:0] i1_0_reg_286;
reg   [19:0] result_0_i_reg_297;
reg   [1:0] i_0_i_reg_309;
wire  signed [63:0] sext_ln40_fu_394_p1;
wire   [63:0] zext_ln62_fu_579_p1;
reg   [7:0] kernel_2_2_fu_96;
wire    ap_CS_fsm_state4;
reg   [7:0] kernel_2_2_1_fu_100;
reg   [7:0] kernel_2_2_2_fu_104;
reg   [7:0] kernel_2_2_3_fu_108;
reg   [7:0] kernel_2_2_4_fu_112;
reg   [7:0] kernel_2_2_5_fu_116;
reg   [7:0] kernel_2_2_6_fu_120;
reg   [7:0] kernel_2_2_7_fu_124;
reg   [7:0] kernel_2_2_8_fu_128;
reg   [7:0] window_2_0_fu_140;
wire   [7:0] window_0_0_fu_525_p5;
reg   [7:0] window_2_1_fu_144;
wire   [7:0] window_0_1_fu_537_p5;
reg   [7:0] window_0_2_1_fu_148;
reg   [7:0] window_2_0_1_fu_152;
reg   [7:0] window_2_1_1_fu_156;
reg   [7:0] window_1_2_1_fu_160;
reg   [7:0] window_2_0_2_fu_164;
reg   [7:0] window_2_1_2_fu_168;
reg   [7:0] window_2_2_1_fu_172;
wire   [3:0] tmp_8_fu_355_p3;
wire   [4:0] zext_ln40_1_fu_363_p1;
wire   [4:0] zext_ln40_fu_351_p1;
wire   [4:0] zext_ln40_2_fu_385_p1;
wire   [4:0] add_ln40_fu_389_p2;
wire   [10:0] zext_ln46_fu_444_p1;
wire   [10:0] outrow_fu_472_p2;
wire   [0:0] icmp_ln68_1_fu_600_p2;
wire   [8:0] outcol_fu_611_p2;
wire   [0:0] icmp_ln73_2_fu_617_p2;
wire   [0:0] icmp_ln73_3_fu_623_p2;
wire   [0:0] or_ln73_1_fu_634_p2;
wire   [0:0] or_ln73_fu_629_p2;
wire   [7:0] tmp_6_fu_699_p5;
wire   [7:0] tmp_7_fu_715_p5;
wire   [7:0] tmp_2_fu_760_p5;
wire   [7:0] tmp_3_fu_776_p5;
wire   [7:0] mul_ln16_1_fu_798_p0;
wire   [7:0] mul_ln16_1_fu_798_p1;
wire   [19:0] zext_ln16_10_fu_810_p1;
wire   [7:0] grp_fu_819_p0;
wire   [7:0] grp_fu_819_p1;
wire   [15:0] grp_fu_819_p2;
wire   [7:0] grp_fu_827_p0;
wire   [7:0] grp_fu_827_p1;
wire   [16:0] grp_fu_827_p2;
reg    grp_fu_819_ce;
reg   [14:0] ap_NS_fsm;
wire   [15:0] grp_fu_819_p00;
wire   [15:0] grp_fu_819_p10;
wire   [16:0] grp_fu_819_p20;
wire   [15:0] grp_fu_827_p00;
wire   [15:0] grp_fu_827_p10;
wire   [17:0] grp_fu_827_p20;
wire   [15:0] mul_ln16_1_fu_798_p00;
wire   [15:0] mul_ln16_1_fu_798_p10;
reg    ap_condition_143;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

gauss_blur_part_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
part_buffer_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(part_buffer_0_addr_reg_1020),
    .ce0(part_buffer_0_ce0),
    .we0(part_buffer_0_we0),
    .d0(window_1_2_reg_1030),
    .q0(part_buffer_0_q0)
);

gauss_blur_part_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
part_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(part_buffer_1_address0),
    .ce0(part_buffer_1_ce0),
    .we0(part_buffer_1_we0),
    .d0(window_2_2_reg_273),
    .q0(part_buffer_1_q0)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U1(
    .din0(window_2_1_fu_144),
    .din1(window_2_1_1_fu_156),
    .din2(window_2_1_2_fu_168),
    .din3(i1_0_reg_286),
    .dout(window_0_0_fu_525_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U2(
    .din0(window_0_2_1_fu_148),
    .din1(window_1_2_1_fu_160),
    .din2(window_2_2_1_fu_172),
    .din3(i1_0_reg_286),
    .dout(window_0_1_fu_537_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U3(
    .din0(window_2_1_fu_144),
    .din1(window_2_1_1_fu_156),
    .din2(window_2_1_2_fu_168),
    .din3(i_0_i_reg_309),
    .dout(tmp_4_fu_675_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U4(
    .din0(kernel_2_2_1_fu_100),
    .din1(kernel_2_2_4_fu_112),
    .din2(kernel_2_2_7_fu_124),
    .din3(i_0_i_reg_309),
    .dout(tmp_5_fu_687_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U5(
    .din0(window_0_2_1_fu_148),
    .din1(window_1_2_1_fu_160),
    .din2(window_2_2_1_fu_172),
    .din3(i_0_i_reg_309),
    .dout(tmp_6_fu_699_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U6(
    .din0(kernel_2_2_2_fu_104),
    .din1(kernel_2_2_5_fu_116),
    .din2(kernel_2_2_8_fu_128),
    .din3(i_0_i_reg_309),
    .dout(tmp_7_fu_715_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U7(
    .din0(window_2_0_fu_140),
    .din1(window_2_0_1_fu_152),
    .din2(window_2_0_2_fu_164),
    .din3(i_0_i_reg_309),
    .dout(tmp_2_fu_760_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U8(
    .din0(kernel_2_2_fu_96),
    .din1(kernel_2_2_3_fu_108),
    .din2(kernel_2_2_6_fu_120),
    .din3(i_0_i_reg_309),
    .dout(tmp_3_fu_776_p5)
);

gauss_blur_mac_mueOg #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
gauss_blur_mac_mueOg_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_819_p0),
    .din1(grp_fu_819_p1),
    .din2(grp_fu_819_p2),
    .ce(grp_fu_819_ce),
    .dout(grp_fu_819_p3)
);

gauss_blur_mac_mufYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
gauss_blur_mac_mufYi_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_827_p0),
    .din1(grp_fu_827_p1),
    .din2(grp_fu_827_p2),
    .ce(1'b1),
    .dout(grp_fu_827_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((1'd0 == and_ln68_reg_1035) | ((icmp_ln14_fu_645_p2 == 1'd1) | (or_ln73_2_reg_1039 == 1'd1))))) begin
        col_0_reg_261 <= col_reg_1000;
    end else if (((icmp_ln46_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        col_0_reg_261 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_513_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i1_0_reg_286 <= i_1_fu_519_p2;
    end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        i1_0_reg_286 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_606_p2) & (or_ln73_2_fu_639_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        i_0_i_reg_309 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_0_i_reg_309 <= i_2_reg_1046;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_226 <= i_reg_892;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_226 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_0_reg_238 <= j_reg_959;
    end else if (((icmp_ln38_fu_339_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_238 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_606_p2) & (or_ln73_2_fu_639_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        result_0_i_reg_297 <= 20'd0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        result_0_i_reg_297 <= add_ln16_2_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_339_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_0_reg_250 <= 10'd0;
    end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        row_0_reg_250 <= row_reg_972;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_143)) begin
        if ((1'd0 == and_ln50_fu_508_p2)) begin
            window_2_2_reg_273 <= 8'd0;
        end else if ((1'd1 == and_ln50_fu_508_p2)) begin
            window_2_2_reg_273 <= inImage_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add_ln16_1_reg_1091 <= grp_fu_827_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln16_reg_1086 <= grp_fu_819_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
        and_ln68_reg_1035 <= and_ln68_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        col_reg_1000 <= col_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_reg_1035) & (or_ln73_2_reg_1039 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        i_2_reg_1046 <= i_2_fu_651_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_892 <= i_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        icmp_ln50_1_reg_1005 <= icmp_ln50_1_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        icmp_ln50_reg_977 <= icmp_ln50_fu_460_p2;
        icmp_ln68_reg_982 <= icmp_ln68_fu_466_p2;
        icmp_ln73_1_reg_992 <= icmp_ln73_1_fu_484_p2;
        icmp_ln73_reg_987 <= icmp_ln73_fu_478_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_959 <= j_fu_379_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_238 == 2'd1) & (i_0_reg_226 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_1_fu_100 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(j_0_reg_238 == 2'd1) & ~(j_0_reg_238 == 2'd0) & (i_0_reg_226 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_2_fu_104 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_0_reg_226 == 2'd1) & (j_0_reg_238 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_3_fu_108 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_238 == 2'd1) & (i_0_reg_226 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_4_fu_112 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(j_0_reg_238 == 2'd1) & ~(j_0_reg_238 == 2'd0) & (i_0_reg_226 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_5_fu_116 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_226 == 2'd1) & ~(i_0_reg_226 == 2'd0) & (j_0_reg_238 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_6_fu_120 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_226 == 2'd1) & ~(i_0_reg_226 == 2'd0) & (j_0_reg_238 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_7_fu_124 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_226 == 2'd1) & ~(j_0_reg_238 == 2'd1) & ~(j_0_reg_238 == 2'd0) & ~(i_0_reg_226 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_8_fu_128 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_238 == 2'd0) & (i_0_reg_226 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_fu_96 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        mul_ln16_1_reg_1081 <= mul_ln16_1_fu_798_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_606_p2) & (1'b1 == ap_CS_fsm_state10))) begin
        or_ln73_2_reg_1039 <= or_ln73_2_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_513_p2 == 1'd1) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_0_addr_reg_1020 <= zext_ln62_fu_579_p1;
        window_2_2_1_fu_172 <= window_2_2_reg_273;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_reg_972 <= row_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_339_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sub_ln40_reg_897 <= sub_ln40_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_reg_1035) & (icmp_ln14_fu_645_p2 == 1'd0) & (or_ln73_2_reg_1039 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_4_reg_1051 <= tmp_4_fu_675_p5;
        tmp_5_reg_1056 <= tmp_5_fu_687_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        window_0_2_1_fu_148 <= part_buffer_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        window_1_2_1_fu_160 <= part_buffer_1_q0;
        window_1_2_reg_1030 <= part_buffer_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_513_p2 == 1'd0) & (ap_phi_mux_i1_0_phi_fu_290_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_1_fu_152 <= window_0_0_fu_525_p5;
        window_2_1_1_fu_156 <= window_0_1_fu_537_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_i1_0_phi_fu_290_p4 == 2'd1) & ~(ap_phi_mux_i1_0_phi_fu_290_p4 == 2'd0) & (icmp_ln55_fu_513_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_2_fu_164 <= window_0_0_fu_525_p5;
        window_2_1_2_fu_168 <= window_0_1_fu_537_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_513_p2 == 1'd0) & (ap_phi_mux_i1_0_phi_fu_290_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_fu_140 <= window_0_0_fu_525_p5;
        window_2_1_fu_144 <= window_0_1_fu_537_p5;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_448_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_448_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gauss_kernel_ce0 = 1'b1;
    end else begin
        gauss_kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_819_ce = 1'b1;
    end else begin
        grp_fu_819_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln50_fu_508_p2) & (icmp_ln47_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        inImage_blk_n = inImage_empty_n;
    end else begin
        inImage_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (ap_predicate_op114_read_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        inImage_read = 1'b1;
    end else begin
        inImage_read = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln14_fu_645_p2 == 1'd1) & (1'd1 == and_ln68_reg_1035) & (or_ln73_2_reg_1039 == 1'd0) & (1'b1 == ap_CS_fsm_state11)) | ((or_ln73_2_fu_639_p2 == 1'd1) & (1'd1 == and_ln68_fu_606_p2) & (1'b1 == ap_CS_fsm_state10)))) begin
        outImage_blk_n = outImage_full_n;
    end else begin
        outImage_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op197_write_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        outImage_din = {{result_0_i_reg_297[11:4]}};
    end else if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op169_write_state10 == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        outImage_din = 8'd0;
    end else begin
        outImage_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op197_write_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | (~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op169_write_state10 == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        outImage_write = 1'b1;
    end else begin
        outImage_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)))) begin
        part_buffer_0_ce0 = 1'b1;
    end else begin
        part_buffer_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        part_buffer_0_we0 = 1'b1;
    end else begin
        part_buffer_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_513_p2 == 1'd1) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_1_ce0 = 1'b1;
    end else begin
        part_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_513_p2 == 1'd1) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_1_we0 = 1'b1;
    end else begin
        part_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln38_fu_339_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln39_fu_373_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln46_fu_448_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln55_fu_513_p2 == 1'd1) & (icmp_ln50_1_reg_1005 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((icmp_ln55_fu_513_p2 == 1'd1) & (icmp_ln50_1_reg_1005 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state11) & ((1'd0 == and_ln68_reg_1035) | ((icmp_ln14_fu_645_p2 == 1'd1) | (or_ln73_2_reg_1039 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if ((~((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_reg_1035) & (icmp_ln14_fu_645_p2 == 1'd0) & (or_ln73_2_reg_1039 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_2_fu_813_p2 = (result_0_i_reg_297 + zext_ln16_10_fu_810_p1);

assign add_ln40_fu_389_p2 = (sub_ln40_reg_897 + zext_ln40_2_fu_385_p1);

assign and_ln50_fu_508_p2 = (icmp_ln50_reg_977 & icmp_ln50_1_fu_502_p2);

assign and_ln68_fu_606_p2 = (icmp_ln68_reg_982 & icmp_ln68_1_fu_600_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((ap_predicate_op197_write_state11 == 1'b1) & (outImage_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_143 = (~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_490_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7));
end

assign ap_phi_mux_i1_0_phi_fu_290_p4 = i1_0_reg_286;

always @ (*) begin
    ap_predicate_op114_read_state7 = ((1'd1 == and_ln50_fu_508_p2) & (icmp_ln47_fu_490_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op169_write_state10 = ((or_ln73_2_fu_639_p2 == 1'd1) & (1'd1 == and_ln68_fu_606_p2));
end

always @ (*) begin
    ap_predicate_op197_write_state11 = ((icmp_ln14_fu_645_p2 == 1'd1) & (1'd1 == and_ln68_reg_1035) & (or_ln73_2_reg_1039 == 1'd0));
end

assign col_fu_496_p2 = (col_0_reg_261 + 9'd1);

assign gauss_kernel_address0 = sext_ln40_fu_394_p1;

assign grp_fu_819_p0 = grp_fu_819_p00;

assign grp_fu_819_p00 = tmp_6_fu_699_p5;

assign grp_fu_819_p1 = grp_fu_819_p10;

assign grp_fu_819_p10 = tmp_7_fu_715_p5;

assign grp_fu_819_p2 = grp_fu_819_p20;

assign grp_fu_819_p20 = mul_ln16_1_reg_1081;

assign grp_fu_827_p0 = grp_fu_827_p00;

assign grp_fu_827_p00 = tmp_2_fu_760_p5;

assign grp_fu_827_p1 = grp_fu_827_p10;

assign grp_fu_827_p10 = tmp_3_fu_776_p5;

assign grp_fu_827_p2 = grp_fu_827_p20;

assign grp_fu_827_p20 = add_ln16_reg_1086;

assign i_1_fu_519_p2 = (i1_0_reg_286 + 2'd1);

assign i_2_fu_651_p2 = (i_0_i_reg_309 + 2'd1);

assign i_fu_345_p2 = (i_0_reg_226 + 2'd1);

assign icmp_ln14_fu_645_p2 = ((i_0_i_reg_309 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_339_p2 = ((i_0_reg_226 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_373_p2 = ((j_0_reg_238 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_448_p2 = ((row_0_reg_250 == 10'd641) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_490_p2 = ((col_0_reg_261 == 9'd481) ? 1'b1 : 1'b0);

assign icmp_ln50_1_fu_502_p2 = ((col_0_reg_261 < 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_460_p2 = ((row_0_reg_250 < 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_513_p2 = ((i1_0_reg_286 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_600_p2 = ((col_0_reg_261 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_466_p2 = ((row_0_reg_250 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_484_p2 = ((outrow_fu_472_p2 == 11'd639) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_617_p2 = ((outcol_fu_611_p2 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_3_fu_623_p2 = ((outcol_fu_611_p2 == 9'd479) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_478_p2 = ((outrow_fu_472_p2 == 11'd0) ? 1'b1 : 1'b0);

assign j_fu_379_p2 = (j_0_reg_238 + 2'd1);

assign mul_ln16_1_fu_798_p0 = mul_ln16_1_fu_798_p00;

assign mul_ln16_1_fu_798_p00 = tmp_4_reg_1051;

assign mul_ln16_1_fu_798_p1 = mul_ln16_1_fu_798_p10;

assign mul_ln16_1_fu_798_p10 = tmp_5_reg_1056;

assign mul_ln16_1_fu_798_p2 = (mul_ln16_1_fu_798_p0 * mul_ln16_1_fu_798_p1);

assign or_ln73_1_fu_634_p2 = (icmp_ln73_3_fu_623_p2 | icmp_ln73_1_reg_992);

assign or_ln73_2_fu_639_p2 = (or_ln73_fu_629_p2 | or_ln73_1_fu_634_p2);

assign or_ln73_fu_629_p2 = (icmp_ln73_reg_987 | icmp_ln73_2_fu_617_p2);

assign outcol_fu_611_p2 = ($signed(col_0_reg_261) + $signed(9'd511));

assign outrow_fu_472_p2 = ($signed(zext_ln46_fu_444_p1) + $signed(11'd2047));

assign part_buffer_1_address0 = zext_ln62_fu_579_p1;

assign row_fu_454_p2 = (row_0_reg_250 + 10'd1);

assign sext_ln40_fu_394_p1 = $signed(add_ln40_fu_389_p2);

assign sub_ln40_fu_367_p2 = (zext_ln40_1_fu_363_p1 - zext_ln40_fu_351_p1);

assign tmp_8_fu_355_p3 = {{i_0_reg_226}, {2'd0}};

assign zext_ln16_10_fu_810_p1 = add_ln16_1_reg_1091;

assign zext_ln40_1_fu_363_p1 = tmp_8_fu_355_p3;

assign zext_ln40_2_fu_385_p1 = j_0_reg_238;

assign zext_ln40_fu_351_p1 = i_0_reg_226;

assign zext_ln46_fu_444_p1 = row_0_reg_250;

assign zext_ln62_fu_579_p1 = col_0_reg_261;

endmodule //gauss_blur
