#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("D_I_address0", 8, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("D_I_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("D_I_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("C_I_req_din", 1, hls_out, 1, "ap_bus", "fifo_data", 1),
	Port_Property("C_I_req_full_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("C_I_req_write", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("C_I_rsp_empty_n", 1, hls_in, 1, "ap_bus", "fifo_status", 1),
	Port_Property("C_I_rsp_read", 1, hls_out, 1, "ap_bus", "fifo_update", 1),
	Port_Property("C_I_address", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("C_I_datain", 32, hls_in, 1, "ap_bus", "unknown", 1),
	Port_Property("C_I_dataout", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("C_I_size", 32, hls_out, 1, "ap_bus", "unknown", 1),
	Port_Property("D_O_address0", 8, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("D_O_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("D_O_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("D_O_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
};
const char* HLS_Design_Meta::dut_name = "lab3_z2";
