// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gauss_blur,hls_ip_2020_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7a12t-csg325-1Q,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.475800,HLS_SYN_LAT=5859416,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=1,HLS_SYN_FF=328,HLS_SYN_LUT=793,HLS_VERSION=2020_1}" *)

module gauss_blur (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inImage_dout,
        inImage_empty_n,
        inImage_read,
        gauss_kernel_address0,
        gauss_kernel_ce0,
        gauss_kernel_q0,
        outImage_din,
        outImage_full_n,
        outImage_write
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inImage_dout;
input   inImage_empty_n;
output   inImage_read;
output  [3:0] gauss_kernel_address0;
output   gauss_kernel_ce0;
input  [7:0] gauss_kernel_q0;
output  [7:0] outImage_din;
input   outImage_full_n;
output   outImage_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inImage_read;
reg gauss_kernel_ce0;
reg[7:0] outImage_din;
reg outImage_write;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    inImage_blk_n;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln47_fu_518_p2;
wire   [0:0] and_ln50_fu_536_p2;
reg    outImage_blk_n;
wire    ap_CS_fsm_state10;
wire   [0:0] and_ln68_fu_634_p2;
wire   [0:0] or_ln73_2_fu_667_p2;
wire    ap_CS_fsm_state15;
reg   [0:0] and_ln68_reg_1072;
reg   [0:0] or_ln73_2_reg_1076;
wire   [1:0] i_fu_373_p2;
reg   [1:0] i_reg_929;
wire    ap_CS_fsm_state2;
wire   [4:0] sub_ln40_fu_395_p2;
reg   [4:0] sub_ln40_reg_934;
wire   [0:0] icmp_ln38_fu_367_p2;
wire   [1:0] j_fu_407_p2;
reg   [1:0] j_reg_996;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln39_fu_401_p2;
wire   [9:0] row_fu_482_p2;
reg   [9:0] row_reg_1009;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln50_fu_488_p2;
reg   [0:0] icmp_ln50_reg_1014;
wire   [0:0] icmp_ln46_fu_476_p2;
wire   [0:0] icmp_ln68_fu_494_p2;
reg   [0:0] icmp_ln68_reg_1019;
wire   [0:0] icmp_ln73_fu_506_p2;
reg   [0:0] icmp_ln73_reg_1024;
wire   [0:0] icmp_ln73_1_fu_512_p2;
reg   [0:0] icmp_ln73_1_reg_1029;
wire   [8:0] col_fu_524_p2;
reg   [8:0] col_reg_1037;
reg    ap_predicate_op114_read_state7;
reg    ap_block_state7;
wire   [0:0] icmp_ln50_1_fu_530_p2;
reg   [0:0] icmp_ln50_1_reg_1042;
wire   [1:0] i_1_fu_547_p2;
wire    ap_CS_fsm_state8;
reg   [8:0] part_buffer_0_addr_reg_1057;
wire   [0:0] icmp_ln55_fu_541_p2;
wire   [7:0] part_buffer_1_q0;
reg   [7:0] window_1_2_reg_1067;
wire    ap_CS_fsm_state9;
reg    ap_predicate_op169_write_state10;
reg    ap_block_state10;
wire   [1:0] i_2_fu_679_p2;
reg   [1:0] i_2_reg_1083;
wire    ap_CS_fsm_state11;
wire   [3:0] sub_ln16_fu_697_p2;
reg   [3:0] sub_ln16_reg_1088;
wire   [0:0] icmp_ln14_fu_673_p2;
wire   [7:0] sub_ln21_1_fu_719_p2;
reg   [7:0] sub_ln21_1_reg_1093;
wire   [1:0] j_1_fu_731_p2;
reg   [1:0] j_1_reg_1101;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln15_fu_725_p2;
wire   [31:0] grp_fu_864_p3;
wire    ap_CS_fsm_state14;
reg    part_buffer_0_ce0;
reg    part_buffer_0_we0;
wire   [7:0] part_buffer_0_q0;
wire   [8:0] part_buffer_1_address0;
reg    part_buffer_1_ce0;
reg    part_buffer_1_we0;
reg   [1:0] i_0_reg_232;
reg   [1:0] j_0_reg_244;
wire    ap_CS_fsm_state5;
reg   [9:0] row_0_reg_256;
reg   [8:0] col_0_reg_267;
reg    ap_predicate_op228_write_state15;
reg    ap_block_state15;
reg   [7:0] window_2_2_reg_279;
wire   [1:0] ap_phi_mux_i1_0_phi_fu_296_p4;
reg   [1:0] i1_0_reg_292;
reg   [31:0] result_0_i_reg_303;
reg   [1:0] i_0_i_reg_315;
reg   [31:0] result_1_i_reg_326;
reg   [1:0] j_0_i_reg_338;
wire  signed [63:0] sext_ln40_fu_422_p1;
wire   [63:0] zext_ln62_fu_607_p1;
reg   [7:0] kernel_2_2_fu_102;
wire    ap_CS_fsm_state4;
reg   [7:0] kernel_2_2_1_fu_106;
reg   [7:0] kernel_2_2_2_fu_110;
reg   [7:0] kernel_2_2_3_fu_114;
reg   [7:0] kernel_2_2_4_fu_118;
reg   [7:0] kernel_2_2_5_fu_122;
reg   [7:0] kernel_2_2_6_fu_126;
reg   [7:0] kernel_2_2_7_fu_130;
reg   [7:0] kernel_2_2_8_fu_134;
reg   [7:0] window_2_0_fu_146;
wire   [7:0] window_0_0_fu_553_p5;
reg   [7:0] window_2_1_fu_150;
wire   [7:0] window_0_1_fu_565_p5;
reg   [7:0] window_0_2_1_fu_154;
reg   [7:0] window_2_0_1_fu_158;
reg   [7:0] window_2_1_1_fu_162;
reg   [7:0] window_1_2_1_fu_166;
reg   [7:0] window_2_0_2_fu_170;
reg   [7:0] window_2_1_2_fu_174;
reg   [7:0] window_2_2_1_fu_178;
wire   [7:0] select_ln21_fu_856_p3;
wire   [3:0] tmp_4_fu_383_p3;
wire   [4:0] zext_ln40_1_fu_391_p1;
wire   [4:0] zext_ln40_fu_379_p1;
wire   [4:0] zext_ln40_2_fu_413_p1;
wire   [4:0] add_ln40_fu_417_p2;
wire   [10:0] zext_ln46_fu_472_p1;
wire   [10:0] outrow_fu_500_p2;
wire   [0:0] icmp_ln68_1_fu_628_p2;
wire   [8:0] outcol_fu_639_p2;
wire   [0:0] icmp_ln73_2_fu_645_p2;
wire   [0:0] icmp_ln73_3_fu_651_p2;
wire   [0:0] or_ln73_1_fu_662_p2;
wire   [0:0] or_ln73_fu_657_p2;
wire   [3:0] shl_ln_fu_689_p3;
wire   [3:0] zext_ln16_fu_685_p1;
wire   [31:0] sub_ln21_fu_703_p2;
wire   [7:0] trunc_ln21_1_fu_709_p4;
wire   [3:0] zext_ln16_1_fu_773_p1;
wire   [3:0] add_ln16_fu_777_p2;
wire   [7:0] tmp_2_fu_782_p11;
wire   [7:0] tmp_3_fu_810_p11;
wire   [0:0] tmp_5_fu_838_p3;
wire   [7:0] trunc_ln21_2_fu_846_p4;
wire   [7:0] grp_fu_864_p0;
wire   [7:0] grp_fu_864_p1;
reg   [14:0] ap_NS_fsm;
wire   [15:0] grp_fu_864_p00;
wire   [15:0] grp_fu_864_p10;
reg    ap_condition_140;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

gauss_blur_part_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
part_buffer_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(part_buffer_0_addr_reg_1057),
    .ce0(part_buffer_0_ce0),
    .we0(part_buffer_0_we0),
    .d0(window_1_2_reg_1067),
    .q0(part_buffer_0_q0)
);

gauss_blur_part_bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 480 ),
    .AddressWidth( 9 ))
part_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(part_buffer_1_address0),
    .ce0(part_buffer_1_ce0),
    .we0(part_buffer_1_we0),
    .d0(window_2_2_reg_279),
    .q0(part_buffer_1_q0)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U1(
    .din0(window_2_1_fu_150),
    .din1(window_2_1_1_fu_162),
    .din2(window_2_1_2_fu_174),
    .din3(i1_0_reg_292),
    .dout(window_0_0_fu_553_p5)
);

gauss_blur_mux_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_32dEe_U2(
    .din0(window_0_2_1_fu_154),
    .din1(window_1_2_1_fu_166),
    .din2(window_2_2_1_fu_178),
    .din3(i1_0_reg_292),
    .dout(window_0_1_fu_565_p5)
);

gauss_blur_mux_94eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_94eOg_U3(
    .din0(window_2_0_fu_146),
    .din1(window_2_1_fu_150),
    .din2(window_0_2_1_fu_154),
    .din3(window_2_0_1_fu_158),
    .din4(window_2_1_1_fu_162),
    .din5(window_1_2_1_fu_166),
    .din6(window_2_0_2_fu_170),
    .din7(window_2_1_2_fu_174),
    .din8(window_2_2_1_fu_178),
    .din9(add_ln16_fu_777_p2),
    .dout(tmp_2_fu_782_p11)
);

gauss_blur_mux_94eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
gauss_blur_mux_94eOg_U4(
    .din0(kernel_2_2_fu_102),
    .din1(kernel_2_2_1_fu_106),
    .din2(kernel_2_2_2_fu_110),
    .din3(kernel_2_2_3_fu_114),
    .din4(kernel_2_2_4_fu_118),
    .din5(kernel_2_2_5_fu_122),
    .din6(kernel_2_2_6_fu_126),
    .din7(kernel_2_2_7_fu_130),
    .din8(kernel_2_2_8_fu_134),
    .din9(add_ln16_fu_777_p2),
    .dout(tmp_3_fu_810_p11)
);

gauss_blur_mac_mufYi #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gauss_blur_mac_mufYi_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_864_p0),
    .din1(grp_fu_864_p1),
    .din2(result_1_i_reg_326),
    .ce(1'b1),
    .dout(grp_fu_864_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op228_write_state15 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
        col_0_reg_267 <= col_reg_1037;
    end else if (((icmp_ln46_fu_476_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        col_0_reg_267 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i1_0_reg_292 <= i_1_fu_547_p2;
    end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        i1_0_reg_292 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_634_p2) & (or_ln73_2_fu_667_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        i_0_i_reg_315 <= 2'd0;
    end else if (((icmp_ln15_fu_725_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        i_0_i_reg_315 <= i_2_reg_1083;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln39_fu_401_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_232 <= i_reg_929;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_232 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_0_i_reg_338 <= j_1_reg_1101;
    end else if (((icmp_ln14_fu_673_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        j_0_i_reg_338 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_0_reg_244 <= j_reg_996;
    end else if (((icmp_ln38_fu_367_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_244 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_634_p2) & (or_ln73_2_fu_667_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        result_0_i_reg_303 <= 32'd0;
    end else if (((icmp_ln15_fu_725_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        result_0_i_reg_303 <= result_1_i_reg_326;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        result_1_i_reg_326 <= grp_fu_864_p3;
    end else if (((icmp_ln14_fu_673_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        result_1_i_reg_326 <= result_0_i_reg_303;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_367_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_0_reg_256 <= 10'd0;
    end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        row_0_reg_256 <= row_reg_1009;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_140)) begin
        if ((1'd0 == and_ln50_fu_536_p2)) begin
            window_2_2_reg_279 <= 8'd0;
        end else if ((1'd1 == and_ln50_fu_536_p2)) begin
            window_2_2_reg_279 <= inImage_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10))) begin
        and_ln68_reg_1072 <= and_ln68_fu_634_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        col_reg_1037 <= col_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_2_reg_1083 <= i_2_fu_679_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_929 <= i_fu_373_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        icmp_ln50_1_reg_1042 <= icmp_ln50_1_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_476_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        icmp_ln50_reg_1014 <= icmp_ln50_fu_488_p2;
        icmp_ln68_reg_1019 <= icmp_ln68_fu_494_p2;
        icmp_ln73_1_reg_1029 <= icmp_ln73_1_fu_512_p2;
        icmp_ln73_reg_1024 <= icmp_ln73_fu_506_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        j_1_reg_1101 <= j_1_fu_731_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_996 <= j_fu_407_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_244 == 2'd1) & (i_0_reg_232 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_1_fu_106 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(j_0_reg_244 == 2'd1) & ~(j_0_reg_244 == 2'd0) & (i_0_reg_232 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_2_fu_110 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((i_0_reg_232 == 2'd1) & (j_0_reg_244 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_3_fu_114 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_244 == 2'd1) & (i_0_reg_232 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_4_fu_118 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(j_0_reg_244 == 2'd1) & ~(j_0_reg_244 == 2'd0) & (i_0_reg_232 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_5_fu_122 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_232 == 2'd1) & ~(i_0_reg_232 == 2'd0) & (j_0_reg_244 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_6_fu_126 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_232 == 2'd1) & ~(i_0_reg_232 == 2'd0) & (j_0_reg_244 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_7_fu_130 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_0_reg_232 == 2'd1) & ~(j_0_reg_244 == 2'd1) & ~(j_0_reg_244 == 2'd0) & ~(i_0_reg_232 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_8_fu_134 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((j_0_reg_244 == 2'd0) & (i_0_reg_232 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kernel_2_2_fu_102 <= gauss_kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_634_p2) & (1'b1 == ap_CS_fsm_state10))) begin
        or_ln73_2_reg_1076 <= or_ln73_2_fu_667_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_541_p2 == 1'd1) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_0_addr_reg_1057 <= zext_ln62_fu_607_p1;
        window_2_2_1_fu_178 <= window_2_2_reg_279;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_reg_1009 <= row_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_fu_673_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        sub_ln16_reg_1088 <= sub_ln16_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_fu_673_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        sub_ln21_1_reg_1093 <= sub_ln21_1_fu_719_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_fu_367_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        sub_ln40_reg_934 <= sub_ln40_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        window_0_2_1_fu_154 <= part_buffer_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        window_1_2_1_fu_166 <= part_buffer_1_q0;
        window_1_2_reg_1067 <= part_buffer_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_541_p2 == 1'd0) & (ap_phi_mux_i1_0_phi_fu_296_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_1_fu_158 <= window_0_0_fu_553_p5;
        window_2_1_1_fu_162 <= window_0_1_fu_565_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_i1_0_phi_fu_296_p4 == 2'd1) & ~(ap_phi_mux_i1_0_phi_fu_296_p4 == 2'd0) & (icmp_ln55_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_2_fu_170 <= window_0_0_fu_553_p5;
        window_2_1_2_fu_174 <= window_0_1_fu_565_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln55_fu_541_p2 == 1'd0) & (ap_phi_mux_i1_0_phi_fu_296_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        window_2_0_fu_146 <= window_0_0_fu_553_p5;
        window_2_1_fu_150 <= window_0_1_fu_565_p5;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gauss_kernel_ce0 = 1'b1;
    end else begin
        gauss_kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln50_fu_536_p2) & (icmp_ln47_fu_518_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        inImage_blk_n = inImage_empty_n;
    end else begin
        inImage_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (ap_predicate_op114_read_state7 == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        inImage_read = 1'b1;
    end else begin
        inImage_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln68_reg_1072) & (or_ln73_2_reg_1076 == 1'd0) & (1'b1 == ap_CS_fsm_state15)) | ((or_ln73_2_fu_667_p2 == 1'd1) & (1'd1 == and_ln68_fu_634_p2) & (1'b1 == ap_CS_fsm_state10)))) begin
        outImage_blk_n = outImage_full_n;
    end else begin
        outImage_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op228_write_state15 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op228_write_state15 == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        outImage_din = select_ln21_fu_856_p3;
    end else if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op169_write_state10 == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        outImage_din = 8'd0;
    end else begin
        outImage_din = 'bx;
    end
end

always @ (*) begin
    if (((~((ap_predicate_op228_write_state15 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op228_write_state15 == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | (~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (ap_predicate_op169_write_state10 == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        outImage_write = 1'b1;
    end else begin
        outImage_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10)))) begin
        part_buffer_0_ce0 = 1'b1;
    end else begin
        part_buffer_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        part_buffer_0_we0 = 1'b1;
    end else begin
        part_buffer_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_541_p2 == 1'd1) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_1_ce0 = 1'b1;
    end else begin
        part_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_541_p2 == 1'd1) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        part_buffer_1_we0 = 1'b1;
    end else begin
        part_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln38_fu_367_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln39_fu_401_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln46_fu_476_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if ((~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln55_fu_541_p2 == 1'd1) & (icmp_ln50_1_reg_1042 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if (((icmp_ln55_fu_541_p2 == 1'd1) & (icmp_ln50_1_reg_1042 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'd1 == and_ln68_fu_634_p2) & (or_ln73_2_fu_667_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if ((~((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state10) & ((or_ln73_2_fu_667_p2 == 1'd1) | (1'd0 == and_ln68_fu_634_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln14_fu_673_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln15_fu_725_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state15 : begin
            if ((~((ap_predicate_op228_write_state15 == 1'b1) & (outImage_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_fu_777_p2 = (sub_ln16_reg_1088 + zext_ln16_1_fu_773_p1);

assign add_ln40_fu_417_p2 = (sub_ln40_reg_934 + zext_ln40_2_fu_413_p1);

assign and_ln50_fu_536_p2 = (icmp_ln50_reg_1014 & icmp_ln50_1_fu_530_p2);

assign and_ln68_fu_634_p2 = (icmp_ln68_reg_1019 & icmp_ln68_1_fu_628_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10 = ((ap_predicate_op169_write_state10 == 1'b1) & (outImage_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state15 = ((ap_predicate_op228_write_state15 == 1'b1) & (outImage_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_140 = (~((ap_predicate_op114_read_state7 == 1'b1) & (inImage_empty_n == 1'b0)) & (icmp_ln47_fu_518_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7));
end

assign ap_phi_mux_i1_0_phi_fu_296_p4 = i1_0_reg_292;

always @ (*) begin
    ap_predicate_op114_read_state7 = ((1'd1 == and_ln50_fu_536_p2) & (icmp_ln47_fu_518_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op169_write_state10 = ((or_ln73_2_fu_667_p2 == 1'd1) & (1'd1 == and_ln68_fu_634_p2));
end

always @ (*) begin
    ap_predicate_op228_write_state15 = ((1'd1 == and_ln68_reg_1072) & (or_ln73_2_reg_1076 == 1'd0));
end

assign col_fu_524_p2 = (col_0_reg_267 + 9'd1);

assign gauss_kernel_address0 = sext_ln40_fu_422_p1;

assign grp_fu_864_p0 = grp_fu_864_p00;

assign grp_fu_864_p00 = tmp_3_fu_810_p11;

assign grp_fu_864_p1 = grp_fu_864_p10;

assign grp_fu_864_p10 = tmp_2_fu_782_p11;

assign i_1_fu_547_p2 = (i1_0_reg_292 + 2'd1);

assign i_2_fu_679_p2 = (i_0_i_reg_315 + 2'd1);

assign i_fu_373_p2 = (i_0_reg_232 + 2'd1);

assign icmp_ln14_fu_673_p2 = ((i_0_i_reg_315 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_725_p2 = ((j_0_i_reg_338 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_367_p2 = ((i_0_reg_232 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_401_p2 = ((j_0_reg_244 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_476_p2 = ((row_0_reg_256 == 10'd641) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_518_p2 = ((col_0_reg_267 == 9'd481) ? 1'b1 : 1'b0);

assign icmp_ln50_1_fu_530_p2 = ((col_0_reg_267 < 9'd480) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_488_p2 = ((row_0_reg_256 < 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_541_p2 = ((i1_0_reg_292 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_628_p2 = ((col_0_reg_267 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_494_p2 = ((row_0_reg_256 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_512_p2 = ((outrow_fu_500_p2 == 11'd639) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_645_p2 = ((outcol_fu_639_p2 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_3_fu_651_p2 = ((outcol_fu_639_p2 == 9'd479) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_506_p2 = ((outrow_fu_500_p2 == 11'd0) ? 1'b1 : 1'b0);

assign j_1_fu_731_p2 = (j_0_i_reg_338 + 2'd1);

assign j_fu_407_p2 = (j_0_reg_244 + 2'd1);

assign or_ln73_1_fu_662_p2 = (icmp_ln73_3_fu_651_p2 | icmp_ln73_1_reg_1029);

assign or_ln73_2_fu_667_p2 = (or_ln73_fu_657_p2 | or_ln73_1_fu_662_p2);

assign or_ln73_fu_657_p2 = (icmp_ln73_reg_1024 | icmp_ln73_2_fu_645_p2);

assign outcol_fu_639_p2 = ($signed(col_0_reg_267) + $signed(9'd511));

assign outrow_fu_500_p2 = ($signed(zext_ln46_fu_472_p1) + $signed(11'd2047));

assign part_buffer_1_address0 = zext_ln62_fu_607_p1;

assign row_fu_482_p2 = (row_0_reg_256 + 10'd1);

assign select_ln21_fu_856_p3 = ((tmp_5_fu_838_p3[0:0] === 1'b1) ? sub_ln21_1_reg_1093 : trunc_ln21_2_fu_846_p4);

assign sext_ln40_fu_422_p1 = $signed(add_ln40_fu_417_p2);

assign shl_ln_fu_689_p3 = {{i_0_i_reg_315}, {2'd0}};

assign sub_ln16_fu_697_p2 = (shl_ln_fu_689_p3 - zext_ln16_fu_685_p1);

assign sub_ln21_1_fu_719_p2 = (8'd0 - trunc_ln21_1_fu_709_p4);

assign sub_ln21_fu_703_p2 = (32'd0 - result_0_i_reg_303);

assign sub_ln40_fu_395_p2 = (zext_ln40_1_fu_391_p1 - zext_ln40_fu_379_p1);

assign tmp_4_fu_383_p3 = {{i_0_reg_232}, {2'd0}};

assign tmp_5_fu_838_p3 = result_0_i_reg_303[32'd31];

assign trunc_ln21_1_fu_709_p4 = {{sub_ln21_fu_703_p2[11:4]}};

assign trunc_ln21_2_fu_846_p4 = {{result_0_i_reg_303[11:4]}};

assign zext_ln16_1_fu_773_p1 = j_0_i_reg_338;

assign zext_ln16_fu_685_p1 = i_0_i_reg_315;

assign zext_ln40_1_fu_391_p1 = tmp_4_fu_383_p3;

assign zext_ln40_2_fu_413_p1 = j_0_reg_244;

assign zext_ln40_fu_379_p1 = i_0_reg_232;

assign zext_ln46_fu_472_p1 = row_0_reg_256;

assign zext_ln62_fu_607_p1 = col_0_reg_267;

endmodule //gauss_blur
