// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Loop_Loop2_proc_HH_
#define _Loop_Loop2_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Loop_Loop2_proc : public sc_module {
    // Port declarations 24
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<14> > temp1_address0;
    sc_out< sc_logic > temp1_ce0;
    sc_in< sc_lv<32> > temp1_q0;
    sc_in< sc_lv<32> > tmp3_loc_dout;
    sc_in< sc_logic > tmp3_loc_empty_n;
    sc_out< sc_logic > tmp3_loc_read;
    sc_out< sc_lv<14> > temp3_address0;
    sc_out< sc_logic > temp3_ce0;
    sc_out< sc_logic > temp3_we0;
    sc_out< sc_lv<32> > temp3_d0;
    sc_out< sc_lv<14> > temp2_address0;
    sc_out< sc_logic > temp2_ce0;
    sc_in< sc_lv<32> > temp2_q0;
    sc_out< sc_lv<14> > temp4_address0;
    sc_out< sc_logic > temp4_ce0;
    sc_out< sc_logic > temp4_we0;
    sc_out< sc_lv<32> > temp4_d0;


    // Module declarations
    Loop_Loop2_proc(sc_module_name name);
    SC_HAS_PROCESS(Loop_Loop2_proc);

    ~Loop_Loop2_proc();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > tmp3_loc_blk_n;
    sc_signal< sc_lv<15> > j_0_i_i_reg_121;
    sc_signal< sc_lv<32> > tmp3_loc_read_reg_154;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > icmp_ln28_fu_132_p2;
    sc_signal< sc_lv<1> > icmp_ln28_reg_159;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter3;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > icmp_ln28_reg_159_pp0_iter1_reg;
    sc_signal< sc_lv<1> > icmp_ln28_reg_159_pp0_iter2_reg;
    sc_signal< sc_lv<15> > j_fu_138_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<64> > zext_ln29_fu_144_p1;
    sc_signal< sc_lv<64> > zext_ln29_reg_168;
    sc_signal< sc_lv<64> > zext_ln29_reg_168_pp0_iter1_reg;
    sc_signal< sc_lv<64> > zext_ln29_reg_168_pp0_iter2_reg;
    sc_signal< sc_lv<32> > temp1_load_reg_184;
    sc_signal< sc_lv<32> > mul_ln29_fu_150_p2;
    sc_signal< sc_lv<32> > mul_ln29_reg_189;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<15> ap_const_lv15_4000;
    static const sc_lv<15> ap_const_lv15_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5_pp0_stage0_iter3();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_icmp_ln28_fu_132_p2();
    void thread_j_fu_138_p2();
    void thread_mul_ln29_fu_150_p2();
    void thread_temp1_address0();
    void thread_temp1_ce0();
    void thread_temp2_address0();
    void thread_temp2_ce0();
    void thread_temp3_address0();
    void thread_temp3_ce0();
    void thread_temp3_d0();
    void thread_temp3_we0();
    void thread_temp4_address0();
    void thread_temp4_ce0();
    void thread_temp4_d0();
    void thread_temp4_we0();
    void thread_tmp3_loc_blk_n();
    void thread_tmp3_loc_read();
    void thread_zext_ln29_fu_144_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
